config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :description, :priority, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.new(todo_params) # replacing ".create" with ".new" allows verification that the todo saved

    if @todo.save
      respond_to do |format|
        format.html{redirect_to root_path}
        format.js{}
      end
    else
      @todos = Todo.all
      render :index
    end
    # redirect_to root_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html{redirect_to root_path}
      format.js
    end
    # redirect_to root_path
  end

  private

    def todo_params
      params.require(:todo).permit(:description, :priority)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_todo.html.erb
<li id="<%= todo.id %>">
  <%= todo.description %><br>
  <strong>priority: </strong> <%= todo.priority %><br>
  <%= link_to 'done', todo_path(todo), method: 'delete', remote: true %>
</li>

app/views/todos/create.js.erb
$('ul').append("<%= j render partial: 'todo', locals:{todo: @todo}%>");

app/views/todos/destroy.js.erb
var id = "<%= @todo.id %>";
$("#" + id).slideUp();

app/views/todos/index.html.erb
  <h1>My Todos</h1>

  <!--
  So, what does remote: true do for you? In short, it adds a data-remote="true" attribute to the generated html form as seen here, and submits the form via Ajax automagically. As with everything in Rails, there's metaprogramming going on under the hood. In this case, the JavaScript code that we wrote to hijack the submit event and make the appropriate Ajax request is all generated for you behind the scenes. If you're feeling extra curious, check out the Rails.js source code.
  https://github.com/rails/jquery-ujs/blob/148571ded762f22ccca84db38d4b4d56853ab395/src/rails.js
  -->

  <%= form_for Todo.new, remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :description, placeholder: "what needs doing?" %>
    </div>

    <div class="form-group">
      <%= f.text_field :priority, placeholder: "priority level" %>
    </div>

    <div class="form-group">
    <%= f.submit %>
    </div>
  <% end %>

  <ul>
  <% @todos.each do |todo| %>
    <%= render todo%>
  <% end %>
  </ul>